### ISSUE TITLE
github.io site?

### ISSUE THREAD

**Issue by noslowerdna** [edcarstens/JugglePro#17]
You should be able to create a github.io site to host this project, so that people don't need to clone and run locally to try it out.

**Comment by edcarstens** [comment]
Hi Andrew

I do have an old version on a github page. Can't recall the URL

**Comment by edcarstens** [comment]
http://edcarstens.github.io/JugglePro/

**Comment by noslowerdna** [comment]
Cool, thanks. Add this link to the README?

**Comment by edcarstens** [comment]
Hello Andrew,
I just updated JugglePro. Check it out!
|   |
|   |   |   |   |   |
| JuggleProJugglePro 3-Ball Cascade Juggling to a Rhythm Simple Feed Dynamic Pattern Modification Async-to-sync Transition Impossible 17-Ball Siteswap  |
|  |
| View on edcarstens.github.io | Preview by Yahoo |
|  |
|   |


-Ed
 

     On Friday, January 9, 2015 11:48 AM, Andrew Olson <notifications@github.com> wrote:
   

 Cool, thanks. Add this link to the README?—
